name: Cypress Test Automation

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:12.17.1 # Usa una imagen preconfigurada para Cypress

    steps:
      # Paso 1: Clonar el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      # Paso 2: Instalar herramientas adicionales
      - name: Instalar herramientas adicionales
        run: |
          apt-get update && apt-get install -y curl
          npm install -g http-server wait-on

      # Paso 3: Iniciar el servidor local
      - name: Iniciar servidor local
        run: http-server "./Nicole proyecto" -p 3000 &
        env:
          CI: true

      # Paso 4: Verificar que el servidor está escuchando
      - name: Verificar que el servidor responde (intento inicial)
        run: |
          echo "Verificando si el servidor responde..."
          curl -I http://localhost:3000/index.html || echo "Servidor no disponible aún, esperando..."

      # Paso 5: Esperar a que el servidor esté disponible
      - name: Esperar que el servidor esté disponible
        run: |
          echo "Esperando que el servidor esté disponible..."
          for i in {1..20}; do
            curl -I http://localhost:3000/index.html && break
            echo "Servidor aún no disponible, reintentando en 5 segundos..."
            sleep 5
          done
        timeout-minutes: 2

      # Paso 6: Configurar Cypress Base URL
      - name: Configurar la URL base para Cypress
        run: echo "CYPRESS_BASE_URL=http://localhost:3000" >> $GITHUB_ENV

      # Paso 7: Ejecutar pruebas con Cypress (excluyendo spec.cy.js)
      - name: Ejecutar pruebas de Cypress (sin spec.cy.js)
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js,!cypress/e2e/spec.cy.js"
